package me.km.blocks;

import net.minecraft.block.Block;
import net.minecraft.block.SoundType;
import net.minecraft.block.TallGrassBlock;
import net.minecraft.block.material.Material;
import net.minecraft.block.BlockState;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.IBlockReader;
import net.minecraft.world.IWorldReader;

public class BlockResistantTallGrass extends TallGrassBlock {
    public BlockResistantTallGrass(String registry) {
        super(Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement()
                .hardnessAndResistance(0.0f, 0.0f).sound(SoundType.PLANT));
        super.setRegistryName(registry);
    }

    @Override
    protected boolean isValidGround(BlockState state, IBlockReader worldIn, BlockPos pos) {
        return true;
    }

    @Override
    public boolean isValidPosition(BlockState state, IWorldReader w, BlockPos pos) {
        return true;
    }
}
