package me.km.blocks;

import net.minecraft.block.Block;
import net.minecraft.block.SaplingBlock;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.Material;
import net.minecraft.block.trees.Tree;

// this class just exists because the SaplingBlock constructor is protected
public class BlockModSapling extends SaplingBlock {
    public BlockModSapling(Tree tree) {
        super(tree, Block.Properties.create(Material.PLANTS).doesNotBlockMovement()
                .tickRandomly().hardnessAndResistance(0.0f, 0.0f).sound(SoundType.PLANT));
    }
}
